# Generated by Django 5.2 on 2025-04-29 18:57

import pgvector.django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_chunk_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunk',
            name='embedding',
            field=pgvector.django.VectorField(dimensions=1536, verbose_name=models.FloatField()),
        ),
    ]
