# Generated by Django 5.2 on 2025-04-30 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_document_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='token_count',
            field=models.IntegerField(default=0),
        ),
    ]
